### ISSUE TITLE
Green boxes!

### ISSUE THREAD

**Issue by TallerAndBlueOnline** [romracer/KalielsTracker#2]
I updated the media files, and...
![Tracker Media Error](https://github.com/user-attachments/assets/0aff262c-1369-40de-aec8-9f09bdbd1ce3)
Green boxes.  I somehow doubt it's supposed to look like that. 

Additionally: it's still hiding TomTom/Mapster quest markers on the map (or is doing it again, as the case may be). Thanks in advance.

**Comment by romracer** [comment]
Try the new version from Kaliel released today (Aug 21).  It is specifically for TWW.
