### ISSUE TITLE
Issue After Patch 11.0.2

### ISSUE THREAD

**Issue by swotam** [romracer/KalielsTracker#4]
Getting the following 3 separate errors upon login with no other addons loaded (aside from BugGrabber and BugSack). This is on a brand new toon with all addon options reset. Note that PetTracker is _not loaded_ but does seem to be called by the addon.

4x !KalielsTracker/Modules/Addon_PetTracker.lua:26: attempt to call global 'GetSpellInfo' (a nil value)
[string "@!KalielsTracker/Modules/Addon_PetTracker.lua"]:26: in main chunk

Locals:
addonName = "!KalielsTracker"
KT = <table> {
 modules = <table> {
 }
 WORLD_QUEST_REWARD_TYPE_FLAG_MATERIALS = 8
 WORLD_QUEST_REWARD_TYPE_FLAG_EQUIPMENT = 16
 gameVersion = "11.0.2"
 ActiveButton = <table> {
 }
 Filters = <table> {
 }
 QUEST_DASH = "- "
 PLAYER_FACTION_COLORS = <table> {
 }
 WORLD_QUEST_REWARD_TYPE_FLAG_REPUTATION = 32
 ORDER_RESOURCES_CURRENCY_ID = 1220
 forcedUpdate = false
 WAR_RESOURCES_CURRENCY_ID = 1560
 QUALITY_COLORS = <table> {
 }
 AddonPetTracker = <table> {
 }
 enabledState = true
 ALL_BLIZZARD_MODULES = <table> {
 }
 frame = !KalielsTrackerFrame {
 }
 Hacks = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 WORLD_QUEST_REWARD_TYPE_FLAG_OTHERS = 65536
 locale = "enUS"
 version = "6.6.0"
 name = "!KalielsTracker"
 orderedModules = <table> {
 }
 AZERITE_CURRENCY_ID = 1553
 WORLD_QUEST_REWARD_TYPE_FLAG_MONEY = 1
 WORLD_QUEST_REWARD_TYPE_FLAG_RESOURCES = 2
 WORLD_QUEST_REWARD_TYPE_FLAG_ARTIFACT_POWER = 4
 defaultModuleState = false
 QuestLog = <table> {
 }
 BLIZZARD_MODULES = <table> {
 }
 title = "Kaliel's Tracker"
}
M = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = false
 moduleName = "!KalielsTracker_AddonPetTracker"
 defaultModuleState = true
 name = "!KalielsTracker_!KalielsTracker_AddonPetTracker"
 orderedModules = <table> {
 }
}
LSM = <table> {
 OverrideMedia = <table> {
 }
 callbacks = <table> {
 }
 LOCALE_BIT_zhTW = 8
 LOCALE_BIT_ruRU = 2
 MediaType = <table> {
 }
 LOCALE_BIT_western = 128
 MediaTable = <table> {
 }
 LOCALE_BIT_zhCN = 4
 DefaultMedia = <table> {
 }
 MediaList = <table> {
 }
 LOCALE_BIT_koKR = 1
}
db = nil
dbChar = nil
OTF = KT_ObjectiveTrackerFrame {
 lineWidth = 0
 lineTemplate = "KT_ObjectiveTrackerLineTemplate"
 freeProgressBars = <table> {
 }
 layoutIndex = 50
 usedTimerBars = <table> {
 }
 isUpdating = false
 blockTemplate = "KT_ObjectiveTrackerBlockTemplate"
 fromModuleOffsetY = -10
 HeaderMenu = Frame {
 }
 oldContentsHeight = 0
 BlocksFrame = KT_ObjectiveTrackerBlocksFrame {
 }
 updateReasonEvents = 0
 blockType = "Frame"
 blockOffset = <table> {
 }
 friendlyName = "KT_DEFAULT_OBJECTIVE_TRACKER_MODULE"
 usedBlocks = <table> {
 }
 usedProgressBars = <table> {
 }
 contentsHeight = 0
 hasSkippedBlocks = false
 contentsAnimHeight = 0
 lineSpacing = 2
 poolCollection = <table> {
 }
 freeLines = <table> {
 }
 freeTimerBars = <table> {
 }
 fromHeaderOffsetY = -10
 updateReasonModule = 0
}
PetTracker = nil
header = nil
content = nil
filterButton = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = 122026
(*temporary) = "attempt to call global 'GetSpellInfo' (a nil value)"

-----

2x ...cker/Core/Blizzard_CampaignQuestObjectiveTracker.lua:8: attempt to call method 'GetSortType' (a nil value)
[string "@!KalielsTracker/Core/Blizzard_CampaignQuestObjectiveTracker.lua"]:8: in function `ShouldDisplayQuest'
[string "@!KalielsTracker/Core/Blizzard_QuestObjectiveTracker.lua"]:237: in function `BuildQuestWatchInfos'
[string "@!KalielsTracker/Core/Blizzard_QuestObjectiveTracker.lua"]:248: in function `EnumQuestWatchData'
[string "@!KalielsTracker/Core/Blizzard_QuestObjectiveTracker.lua"]:478: in function `Update'
[string "@!KalielsTracker/Core/Blizzard_ObjectiveTracker.lua"]:1431: in function <...s/!KalielsTracker/Core/Blizzard_ObjectiveTracker.lua:1382>
[string "@!KalielsTracker/KalielsTracker.lua"]:739: in function `KT_ObjectiveTracker_Update'
[string "@!KalielsTracker/Core/Blizzard_ObjectiveTracker.lua"]:985: in function <...s/!KalielsTracker/Core/Blizzard_ObjectiveTracker.lua:984>

Locals:
self = <table> {
 BlocksFrame = KT_ObjectiveTrackerBlocksFrame {
 }
 playerMoney = 10000
 title = "Campaign"
 freeLines = <table> {
 }
 lineTemplate = "KT_ObjectiveTrackerLineTemplate"
 hasSkippedBlocks = false
 buttonOffsets = <table> {
 }
 contentsAnimHeight = 0
 lineWidth = 227.466666
 fromModuleOffsetY = -10
 watchMoney = false
 numPOINumeric = 0
 Header = Frame {
 }
 potentialBlocksAddedThisLayout = 0
 freeTimerBars = <table> {
 }
 blockTemplate = "KT2_ObjectiveTrackerBlockTemplate"
 initializedPopUpTracker = true
 usedProgressBars = <table> {
 }
 usedTimerBars = <table> {
 }
 poolCollection = <table> {
 }
 usedBlocks = <table> {
 }
 oldContentsHeight = 0
 contentsHeight = 0
 updateReasonEvents = 515
 fromHeaderOffsetY = -10
 friendlyName = "KT_CAMPAIGN_QUEST_TRACKER_MODULE"
 paddingBetweenButtons = <table> {
 }
 blockOffset = <table> {
 }
 blockType = "Frame"
 freeProgressBars = <table> {
 }
 lineSpacing = 2
 updateReasonModule = 1024
}
quest = <table> {
 isAbandonOnDisable = false
 useMinimalHeader = false
 level = 10
 isTask = false
 questID = 82539
 isBounty = false
 requiredMoney = -1
 frequency = 0
 sortAsNormalQuest = true
 difficultyLevel = 10
 isRepeatable = false
 questClassification = 7
 overridesSortOrder = false
 isScaling = true
 isHidden = false
 isAutoComplete = false
 isInternalOnly = false
 startEvent = false
 suggestedGroup = 0
 title = "Radiant Echoes"
 readyForTranslation = true
 isLegendary = false
 isHeader = false
 isStory = false
 hasQuestLogInfo = true
}
(*temporary) = nil
(*temporary) = <table> {
 isAbandonOnDisable = false
 useMinimalHeader = false
 level = 10
 isTask = false
 questID = 82539
 isBounty = false
 requiredMoney = -1
 frequency = 0
 sortAsNormalQuest = true
 difficultyLevel = 10
 isRepeatable = false
 questClassification = 7
 overridesSortOrder = false
 isScaling = true
 isHidden = false
 isAutoComplete = false
 isInternalOnly = false
 startEvent = false
 suggestedGroup = 0
 title = "Radiant Echoes"
 readyForTranslation = true
 isLegendary = false
 isHeader = false
 isStory = false
 hasQuestLogInfo = true
}
(*temporary) = "attempt to call method 'GetSortType' (a nil value)"

-----

1x ...zard_UIWidgets/Mainline/Blizzard_UIWidgetManager.lua:370: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Blizzard_UIWidgets/Mainline/Blizzard_UIWidgetManager.lua"]:370: in function `MarkAllWidgetsForRemoval'
[string "@Blizzard_UIWidgets/Mainline/Blizzard_UIWidgetManager.lua"]:546: in function `ProcessAllWidgets'
[string "@!KalielsTracker/KalielsTracker.lua"]:342: in function <!KalielsTracker/KalielsTracker.lua:329>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

-----

When attempting to track or untrack a quest through the Quest Log, the following error is experienced repeatedly:

97x !KalielsTracker/KalielsTracker.lua:2910: attempt to call method 'IsShown' (a nil value)
[string "@!KalielsTracker/KalielsTracker.lua"]:2910: in function `IsTrackerEmpty'
[string "@!KalielsTracker/KalielsTracker.lua"]:2917: in function `ToggleEmptyTracker'
[string "@!KalielsTracker/KalielsTracker.lua"]:751: in function `KT_ObjectiveTracker_Update'
[string "@!KalielsTracker/KalielsTracker.lua"]:420: in function <!KalielsTracker/KalielsTracker.lua:358>

Locals:
self = <table> {
 modules = <table> {
 }
 WORLD_QUEST_REWARD_TYPE_FLAG_MATERIALS = 8
 Help = <table> {
 }
 inInstance = false
 font = "Interface\AddOns\ElvUI\Core\Media\Fonts\Expressway.ttf"
 WORLD_QUEST_REWARD_TYPE_FLAG_REPUTATION = 32
 collapsedByUser = false
 db = <table> {
 }
 Hacks = <table> {
 }
 activeTasks = <table> {
 }
 questStateStopUpdate = false
 WORLD_QUEST_REWARD_TYPE_FLAG_OTHERS = 65536
 name = "!KalielsTracker"
 stopUpdate = false
 WORLD_QUEST_REWARD_TYPE_FLAG_MONEY = 1
 locale = "enUS"
 WORLD_QUEST_REWARD_TYPE_FLAG_RESOURCES = 2
 fixedButtons = <table> {
 }
 WORLD_QUEST_REWARD_TYPE_FLAG_ARTIFACT_POWER = 4
 inScenario = false
 QuestLog = <table> {
 }
 BLIZZARD_MODULES = <table> {
 }
 inWorld = true
 baseName = "!KalielsTracker"
 locked = false
 gameVersion = "11.0.2"
 title = "Kaliel's Tracker"
 PLAYER_FACTION_COLORS = <table> {
 }
 forcedUpdate = false
 QUALITY_COLORS = <table> {
 }
 AddonPetTracker = <table> {
 }
 DropDown = !KalielsTrackerDropDown {
 }
 headers = <table> {
 }
 initialized = false
 playerLevel = 70
 hidden = false
 defaultModuleLibraries = <table> {
 }
 hiddenQuestPopUps = false
 hdrBtnColor = <table> {
 }
 borderColor = <table> {
 }
 optionsFrame = <table> {
 }
 options = <table> {
 }
 classColor = <table> {
 }
 wqInitialized = false
 playerFaction = "Alliance"
 playerName = "Alluria"
 version = "6.6.0"
 orderedModules = <table> {
 }
 WORLD_QUEST_REWARD_TYPE_FLAG_EQUIPMENT = 16
 AddonOthers = <table> {
 }
 AddonTomTom = <table> {
 }
 ActiveButton = <table> {
 }
 AZERITE_CURRENCY_ID = 1553
 QUEST_DASH = "- "
 Filters = <table> {
 }
 ORDER_RESOURCES_CURRENCY_ID = 1220
 WAR_RESOURCES_CURRENCY_ID = 1560
 enabledState = true
 ALL_BLIZZARD_MODULES = <table> {
 }
 frame = !KalielsTrackerFrame {
 }
 defaultModuleState = false
}
noaddon = nil
result = true
(*temporary) = nil
(*temporary) = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 enabledState = false
 baseName = "!KalielsTracker"
 moduleName = "!KalielsTracker_AddonPetTracker"
 defaultModuleState = true
 name = "!KalielsTracker_!KalielsTracker_AddonPetTracker"
 orderedModules = <table> {
 }
}
(*temporary) = "attempt to call method 'IsShown' (a nil value)"
KT = <table> {
 modules = <table> {
 }
 WORLD_QUEST_REWARD_TYPE_FLAG_MATERIALS = 8
 Help = <table> {
 }
 inInstance = false
 font = "Interface\AddOns\ElvUI\Core\Media\Fonts\Expressway.ttf"
 WORLD_QUEST_REWARD_TYPE_FLAG_REPUTATION = 32
 collapsedByUser = false
 db = <table> {
 }
 Hacks = <table> {
 }
 activeTasks = <table> {
 }
 questStateStopUpdate = false
 WORLD_QUEST_REWARD_TYPE_FLAG_OTHERS = 65536
 name = "!KalielsTracker"
 stopUpdate = false
 WORLD_QUEST_REWARD_TYPE_FLAG_MONEY = 1
 locale = "enUS"
 WORLD_QUEST_REWARD_TYPE_FLAG_RESOURCES = 2
 fixedButtons = <table> {
 }
 WORLD_QUEST_REWARD_TYPE_FLAG_ARTIFACT_POWER = 4
 inScenario = false
 QuestLog = <table> {
 }
 BLIZZARD_MODULES = <table> {
 }
 inWorld = true
 baseName = "!KalielsTracker"
 locked = false
 gameVersion = "11.0.2"
 title = "Kaliel's Tracker"
 PLAYER_FACTION_COLORS = <table> {
 }
 forcedUpdate = false
 QUALITY_COLORS = <table> {
 }
 AddonPetTracker = <table> {
 }
 DropDown = !KalielsTrackerDropDown {
 }
 headers = <table> {
 }
 initialized = false
 playerLevel = 70
 hidden = false
 defaultModuleLibraries = <table> {
 }
 hiddenQuestPopUps = false
 hdrBtnColor = <table> {
 }
 borderColor = <table> {
 }
 optionsFrame = <table> {
 }
 options = <table> {
 }
 classColor = <table> {
 }
 wqInitialized = false
 playerFaction = "Alliance"
 playerName = "Alluria"
 version = "6.6.0"
 orderedModules = <table> {
 }
 WORLD_QUEST_REWARD_TYPE_FLAG_EQUIPMENT = 16
 AddonOthers = <table> {
 }
 AddonTomTom = <table> {
 }
 ActiveButton = <table> {
 }
 AZERITE_CURRENCY_ID = 1553
 QUEST_DASH = "- "
 Filters = <table> {
 }
 ORDER_RESOURCES_CURRENCY_ID = 1220
 WAR_RESOURCES_CURRENCY_ID = 1560
 enabledState = true
 ALL_BLIZZARD_MODULES = <table> {
 }
 frame = !KalielsTrackerFrame {
 }
 defaultModuleState = false
}

**Comment by yoshimo** [comment]
change it to ```TrackPets = C_Spell.GetSpellInfo(122026),``` , just needs a prefix to get past the deprecated function calls.

**Comment by romracer** [comment]
Sorry, been a little busy doing things around the house before early access launches.  Kaliel uploaded a new version today, so I'll be archiving this project.  Try the new version he has released today (Aug 21) as it is specifically for TWW and should resolve this error.
